"""Added trigger to daily_global_placement, added dgp to leaderboard

Revision ID: 5e41fa4c7f61
Revises: 1c27f600521d
Create Date: 2023-06-12 01:23:22.017946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e41fa4c7f61'
down_revision = '1c27f600521d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dgp', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.drop_column('dgp')

    # ### end Alembic commands ###
